//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SampleApp.ResourceStrings", typeof(ResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Key is empty.
        /// </summary>
        internal static string apiKeyEmpty {
            get {
                return ResourceManager.GetString("apiKeyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No endpoints configured. Click here..
        /// </summary>
        internal static string configureEndPoint {
            get {
                return ResourceManager.GetString("configureEndPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied {0}.
        /// </summary>
        internal static string copiedToClipboard {
            get {
                return ResourceManager.GetString("copiedToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while VR library is destroyed.
        /// </summary>
        internal static string deinitVR {
            get {
                return ResourceManager.GetString("deinitVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endpoint URL is empty.
        /// </summary>
        internal static string endPointUrlEmpty {
            get {
                return ResourceManager.GetString("endPointUrlEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed with status code {0}.
        /// </summary>
        internal static string failedWithStatus {
            get {
                return ResourceManager.GetString("failedWithStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait while VR library is initialized.
        /// </summary>
        internal static string initVR {
            get {
                return ResourceManager.GetString("initVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to initialize VR library. Is your end point config correct?.
        /// </summary>
        internal static string initVRFailed {
            get {
                return ResourceManager.GetString("initVRFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VR library initialized.
        /// </summary>
        internal static string initVRSuccess {
            get {
                return ResourceManager.GetString("initVRSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid permission.
        /// </summary>
        internal static string invalidPermission {
            get {
                return ResourceManager.GetString("invalidPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created live event {0}.
        /// </summary>
        internal static string liveCreateSuccess {
            get {
                return ResourceManager.GetString("liveCreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as {0}.
        /// </summary>
        internal static string loggedInAs {
            get {
                return ResourceManager.GetString("loggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no RTMP url for this live event. Check if this an RTMP live event..
        /// </summary>
        internal static string noRTMPUrlToCopy {
            get {
                return ResourceManager.GetString("noRTMPUrlToCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;configs&quot;:[{&quot;url&quot;:&quot;https://samsungvr.com/api&quot;,&quot;apiKey&quot;:&quot;58518419e38ac0000cb5fba8.a7cNtpUHZxAcSLa8x_wc-mOsuWED-4IcNroyJKaLP8U&quot;}]}.
        /// </summary>
        internal static string preConfiguredEP {
            get {
                return ResourceManager.GetString("preConfiguredEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh live events list and select live event.
        /// </summary>
        internal static string refreshListAndSelectLiveEvent {
            get {
                return ResourceManager.GetString("refreshListAndSelectLiveEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string requestCancelled {
            get {
                return ResourceManager.GetString("requestCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        internal static string requestFailure {
            get {
                return ResourceManager.GetString("requestFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request in progress.
        /// </summary>
        internal static string requestInProgress {
            get {
                return ResourceManager.GetString("requestInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string requestSuccess {
            get {
                return ResourceManager.GetString("requestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to queue request, retry in a bit.
        /// </summary>
        internal static string unableToQueueRequest {
            get {
                return ResourceManager.GetString("unableToQueueRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload cancelled.
        /// </summary>
        internal static string uploadCancelled {
            get {
                return ResourceManager.GetString("uploadCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide an upload description.
        /// </summary>
        internal static string uploadDescriptionInvalid {
            get {
                return ResourceManager.GetString("uploadDescriptionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload failed with status {0}.
        /// </summary>
        internal static string uploadFailedWithStatus {
            get {
                return ResourceManager.GetString("uploadFailedWithStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file does not exist.
        /// </summary>
        internal static string uploadFileDoesNotExist {
            get {
                return ResourceManager.GetString("uploadFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open upload file for Read.
        /// </summary>
        internal static string uploadFileOpenFailed {
            get {
                return ResourceManager.GetString("uploadFileOpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload in progress.
        /// </summary>
        internal static string uploadInProgress {
            get {
                return ResourceManager.GetString("uploadInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload retry failed. Try again in a minute..
        /// </summary>
        internal static string uploadRetryFailed {
            get {
                return ResourceManager.GetString("uploadRetryFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload success.
        /// </summary>
        internal static string uploadSuccess {
            get {
                return ResourceManager.GetString("uploadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide an upload title.
        /// </summary>
        internal static string uploadTitleInvalid {
            get {
                return ResourceManager.GetString("uploadTitleInvalid", resourceCulture);
            }
        }
    }
}
