//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UILib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UILib.ResourceStrings", typeof(ResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to enqueue request. Please retry later..
        /// </summary>
        internal static string failedToEnqueue {
            get {
                return ResourceManager.GetString("failedToEnqueue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed with status code {0}.
        /// </summary>
        internal static string failedWithStatus {
            get {
                return ResourceManager.GetString("failedWithStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSO.
        /// </summary>
        internal static string loginSSO {
            get {
                return ResourceManager.GetString("loginSSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samsung VR.
        /// </summary>
        internal static string loginSVR {
            get {
                return ResourceManager.GetString("loginSVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        internal static string ssoInvalidUserNameOrPassword {
            get {
                return ResourceManager.GetString("ssoInvalidUserNameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to verify Samsung SSO account.
        /// </summary>
        internal static string ssoUnableToVerifyAccount {
            get {
                return ResourceManager.GetString("ssoUnableToVerifyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create account; account already created.
        /// </summary>
        internal static string ssoVRAccountAlreadyCreated {
            get {
                return ResourceManager.GetString("ssoVRAccountAlreadyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account locked-out or schedule to be..
        /// </summary>
        internal static string vrAccountLocked {
            get {
                return ResourceManager.GetString("vrAccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excessive / Too many login attempts.
        /// </summary>
        internal static string vrExcessiveLoginAttempts {
            get {
                return ResourceManager.GetString("vrExcessiveLoginAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed. Check user id / password..
        /// </summary>
        internal static string vrLoginFailed {
            get {
                return ResourceManager.GetString("vrLoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing email or password.
        /// </summary>
        internal static string vrMissingEmailPassword {
            get {
                return ResourceManager.GetString("vrMissingEmailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive account. Check email after account creation..
        /// </summary>
        internal static string vrPendingActivation {
            get {
                return ResourceManager.GetString("vrPendingActivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown user.
        /// </summary>
        internal static string vrUnknownUser {
            get {
                return ResourceManager.GetString("vrUnknownUser", resourceCulture);
            }
        }
    }
}
